# Generated by Django 3.0.7 on 2020-06-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20200627_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(upload_to='main/static/img/note'),
        ),
    ]
